# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code distillery
email: s.shin@marathoner.kr
description: Run everywhere, learn for a lifetime. # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sshplendid.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

## custom settings
paginate: 5
paginate_path: "/blog/pages/:num"
permalink: pretty
# show_drafts: BOOL
# future: BOOL
timezone: ASIA/Seoul

# Theme settings
## Author Settings
author: SeHun Shin # add your name
author-img: about/me.png # add your photo
about-author: A web developer, run everywhere, learn for a lifetime.
social-twitter: via_SSH
social-facebook: # add your Facebook handle
social-github: sshplendid
social-linkedin: sehunshin
social-email: s.shin@marathoner.kr

## Disqus
discus-identifier: sshplendid # add your discus identifier

## Tracker
analytics: UA-125097290-1 # Google Analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
