# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Distillery
email: sshplendid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coding with drinking whatever!<br/>
  술 마시는 것을 좋아하고 가끔 개발도 합니다.<br/>
  Suwon to Seoul<br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sshplendid.github.io" # the base hostname & protocol for your site
twitter_username: sshplendid
github_username:  sshplendid

# Build settings
markdown: kramdown

# permalink
permalink: pretty

gems: [jekyll-paginate]
paginate: 5